### ISSUE TITLE
Don't show uncraftable items

### ISSUE THREAD

**Issue by LoneWolfHT** [random-geek/cg_plus#1]
![image](https://user-images.githubusercontent.com/28972859/59520072-09072f00-8e7e-11e9-96c0-2dfc7bd0476d.png)
It would be nice if the crafting guide didn't show items you can't craft

**Comment by LoneWolfHT** [comment]
The main reason for this was the fact that my creative_mode-only tools were showing up in the crafting guide. I don't see any point in keeping any of the other uncraftables shown though
I can do with just a `not_in_craftguide` group if you don't want to go through all the trouble or have a reason not to ignore the uncraftable items

**Comment by random-geek** [comment]
Sorry about not responding to this earlier. I checked, and it looks like the group `not_in_craft_guide` is used by both Unified Inventory and jp's craftguide, so respecting that would make sense. As far as hiding all uncraftable items, though, the current configuration seems generally more intuitive and better for gameplay.

**Comment by random-geek** [comment]
See c7868a2952602e94c0ba8864190257f1664d415e.
